imports:
    - { resource: config_dev.yml }


framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     '%kernel.cache_dir%/test.db'

services:
    # default configuration for services in *this* file
    _defaults:
        # this for liip_functional_test.validator to make that public
        public: true
