main:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /

starter_kit_start:
    resource: "@StarterKitStartBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
